config:
  minimum_power_percentage: 5 # minimum percentage solar power (OpenDTU requires at least 2%)
  maximum_power_percentage: 100 # maximum percentage solar power
  additional_power: 10 # overprovisioning of solar power to avoid drawing power from grid
webserver:
  host: 0.0.0.0 # listen on all interfaces
  port: 8000 # listen on port 8000
mqtt: # MQTT broker (e.g. Mosquitto)
  host: 127.0.0.1
  port: 1883
  keepalive: 60
  username: test
  password: test
shelly3em:
  mqtt_prefix: shelly3em
  shelly_phases: [0,1,2] # phases to combine (0, 1, 2) if you measure multiple phases
opendtu:
  mqtt_prefix: 1234567890 # serial number of inverter in OpenDTU
  max_power: 1500 # max power of inverter in Watt for calculation of percentage
  delay_between_updates: 6 # delay between mqtt updates to the opendtu in seconds